domain: ENC[AES256_GCM,data:Mqz66qWthR30s2U=,iv:4vLP0QJFj+ZlSy6oxx3f5QpsYdpiGceKocvH5AhELaA=,tag:jxIz4bEOBx49EmzGR0DVEw==,type:str]
one_team_name: ENC[AES256_GCM,data:seqCnOTaPw==,iv:/nWA0GKz5tBd0dU2gNnZSIJy7Udvg+t2Ji9fzW4A86M=,tag:r+VIlt9KktcOiRyQZOaGsw==,type:str]
allowed_emails:
    - ENC[AES256_GCM,data:gz3vAhQHCRDR+raFipJpzfT5MIEW,iv:8OTNJfG2rSrI6l96SdbX1DBT/nFS1y9w3CSwB8ZRKT0=,tag:fZElgZLjnW9qTOoqyegI2w==,type:str]
    - ENC[AES256_GCM,data:NIsjQROv69nJPpetNrALIoAGCQ==,iv:wP4Gj0Fq0Qk17EDtSZpvEz0bpazTZd5PS7Il+V1MlTI=,tag:CWv0hJYUAceo1DWnAriL/A==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c0tPbnVFRHFnTmgrSHYy
            bTBnNlRodVlwQWVZRjBybnJ5cmxsT1ZuY3lZCit5VFNnNjFaa25JQ2E5all4enA4
            Wit5U2t6MCttV2krRDRHdi9XSEtYeDgKLS0tIHEySWpGY2FqTzk3OUErWS9xUU42
            a2V3SjlKdzBweUVJNlFZS2xsVUtkcDQKTbsjXiZvF5g82gcTATt3SoKRxycZn8on
            lwLi1e/iMKq45pWYQSZmJxl48dns1W4RA1t2Ype6PA06sKHDQnL41w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T02:22:11Z"
    mac: ENC[AES256_GCM,data:wWWZ8K4shHKXnkCK7BtiSYSU5DGCN8Cz5Z6L2ry5KyDz7XiTed/xQvdBpr7GLwHvg8DI7kwe3TM0lRItShO5LVckd4gZAIlPBpm48pfWvFz6MTeODN5ABbn4yFpI/BPd0pQGAd74kpc9Lpo6IkrTEGPaxWXrKwo/SRy6bo3yHdQ=,iv:7cgbY/ZGy6+1psNmqb+B6+tgN0nDaAY6PM0SkOR9iPU=,tag:6Ze+wGFKjA8mAbC8icTK/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
