domain: ENC[AES256_GCM,data:Ev7WX3pxgAdGdHg=,iv:6JyBP81zv78p/KA8Ab6B/u6aryP0m0S10e1w9MmXqeg=,tag:4/lymo4CwmuUb888BU+EkQ==,type:str]
one_team_name: ENC[AES256_GCM,data:RHtl07SqQQ==,iv:S4pWZRz+DaIp7eAG6FjpjydpGetlO2A+AzQFYdoO/bk=,tag:Fy4aZxp8wwYCX7KMSCEd7A==,type:str]
allowed_emails:
    - ENC[AES256_GCM,data:oWeWv0y6wNLeyvGwZ2nJmr1iOdL4,iv:Mykwpf+ZZMxl3KzBsgbBhABmFSb5HejM0l7lBTGwX4o=,tag:LWzCA5GUlXHNhPJfXcIUJw==,type:str]
    - ENC[AES256_GCM,data:rkSP4LAFHasjR+e93P+1xAV2gA==,iv:Wvv5rG/3UaeRgYOKCR85NOVtM477Qfy26wIKU81SXlg=,tag:M/2FCeZZqwpjRDCnwifsMA==,type:str]
email_routing_destination: ENC[AES256_GCM,data:RUynivyoyQzqRM45ILJbxDnNamu5,iv:Jlg1dUSSNOSeY2HPKgI42MZ3ctTp6ArGJmRvE62KkFE=,tag:zNXZpq95GYw5XNrz6LBzdw==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRW5qUE5pWE1heGJML2VH
            NEYvcmdjQVRLOGErSVlPK0Z0VlMzYTRML2lJClkxVGtGdTFIbEd5ZkJWZ3oxTHlE
            YXViZkNudm5JTWY1NmxkeUZpYmZsTFUKLS0tIFp6YllodnJSWjhzdld1SjRqZmpZ
            RUJOUHRNQ1lJZjIvMXc5WHBDTnp6MFUK5oL/748zikVTQZc+S0TAw5r+SI/28LiW
            szcv1zD5pllaLDPGOxYtRNBfjRgu0xSIC4SiZUTDTnn7ohBw8BQkHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T16:35:25Z"
    mac: ENC[AES256_GCM,data:bVN2s8Ai84RGVmhEB+NizzAA5kRguiVUNvd7aXeNIQdItqfQy18H7GHOU8p+5pknEB2HnrTUPegkxUv+NawoZiLAvhPB9dPp2Q2VVlgpPCd54fC+/6Nefhk9t0pFMUbeA8+COzjPtEYcDf34H9qbcXLyjPvY+dHLT3v4qhFtVLU=,iv:vPNRVxOmvCrYPcANpb8wmLzIPaN7irFPyY2INZNggJQ=,tag:KuTCeLA4RbLwLEsGlx4/XA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
