domain: ENC[AES256_GCM,data:i6WgHFFFA5crJwU=,iv:cPd0+Y6mKkBBvZ8SlknonqQT0NqN+yjl4A0EM7p8IEk=,tag:S5KqJen8E4VXev6cQ9X/oQ==,type:str]
authelia_url: ENC[AES256_GCM,data:IK23tNT0TvKYQbFfh3QVF+RUgEE5sBvB,iv:EdyjdyFL16NE6lV2rJVfs4pZNEeuEzHs7CiLk/wDiDE=,tag:KOu08bRne0+d9xo/2Obn7Q==,type:str]
storage_encryption_key: ENC[AES256_GCM,data:KjOJpvPt7lr4P9eEdWxi+ESRbdsAH37lTW8GAsoNgdY6vzXBkQsxlrrO6ylaEJ/jT1Jy8CjIUY+SxDGa/vHk6A==,iv:0NtNG5o7tiYnwCRRmI7fr9TJZyyjZ4RLCF25RjVaNfQ=,tag:L6Rf5+wW7Qny2oaJGgTDuw==,type:str]
users:
    - username: ENC[AES256_GCM,data:vwaz2FU=,iv:7Uz2ZwE7CXbCIQS2KznWH1Z8jAWwL/zu44mLtGIysXI=,tag:ba6C6yd8/a2iGmT9XDFxcQ==,type:str]
      display_name: ENC[AES256_GCM,data:I8CAV+s=,iv:OPYy0m8ySiuMtQC763JpLPma4yJgH8aliCkQAHlu2MQ=,tag:2iif6s5oOZBSHIr1e0xKrg==,type:str]
      password: ENC[AES256_GCM,data:SjTnCm7JzMxjXtEwJCWw7KI1mv23pdej8Jx/4tA9NjH0rod/VbwWtKmUxwLbHmQ/9tIdeJBgz+21Z17SP21Shqhi/m9OL21nGN+8NtO+wQdpfaxnmiAXoxLnnVbIboDYsQ==,iv:Q83sgLaHPq/2S4Tor0GGRuVujF8R3gLQqvnfq1wb7Z0=,tag:qzmhvd4UtW0ZIk0QiVk9vQ==,type:str]
      email: ENC[AES256_GCM,data:rxOXApHigw46pWsODdiVQNgzwoyQ,iv:Qzn/1tSPKLIfcfaGMXSfkiONDI5D/USWOk0oYBDmshI=,tag:pUHIU/7XKjG1/Wug383Vxg==,type:str]
      groups:
        - ENC[AES256_GCM,data:lJ+kpNqC,iv:uqB6NZOtq0gafGg3GDB3Yk7rGrZCOTrNAvghJQSgdyI=,tag:4h4b0qpJD/WhPrpwqOYhMA==,type:str]
        - ENC[AES256_GCM,data:ov4fFiY=,iv:1AiGmQE0OQDnk3vfp/j7gCo8+23x+LWivDPubdLxadc=,tag:yOxGwM4XjeLuIy4yugkP8A==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R3p3VmUrQXpGa0FsbHd6
            SUxkZDQwY2Z1SDdIZFJSeGdsVUM5SjdnYkZ3CkZ3dXNvUW5KWGRuNEs2cVg3Q0Vi
            QzJRUWVUQXpUemNoRGJhQWhlQnA5aGMKLS0tIDZxdjJtdDcxREE1R0cra2k4bFFv
            NlV3aXVza1dIVW14VEExaSs3LzRTTmMKEgvJAwIToAcgquwMBK6NnnU/AyPua2FA
            NrWWmtb1bIL6IOGojTojyZxoCpyu+jgCHgoLW9xGQ1rQw2+Ej+u7hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T08:06:19Z"
    mac: ENC[AES256_GCM,data:tlKBswyZxj1FKyk6SEPcD+VPggeQxKhILC4oky608+iuGS0nLcN16S3xLPcEN9HYwJhkiY8B+tGAmnlpehthkEcqQtRPQ1oWzp5BQXv2e3/OKRq/1LSDvm4G4tZYUMB2zEdIFbK6rajjrILt7EyWhGDlVIGzgJjq1/3Jl03v+u0=,iv:Ot7UL7busloWsCWmzGzd4dOLIrts7exD97+A8fWUXjo=,tag:V7BDaWDEyHi3MtQdQFUgjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
