domain: ENC[AES256_GCM,data:N9ArOMZ9UGYe27M=,iv:ZrhE7O6bP9+HqdGd2AKr3flaygx6ZNHWIuphEffytLQ=,tag:G+XiHJzctLh4laNq0K+XQw==,type:str]
authelia_url: ENC[AES256_GCM,data:wAWnCimix+XlpGJY5KRr7dXn452f4rsI,iv:ksGAZmqJ2svYXmQJ4vG4/sm2lOUQD3p6APW5JFCS4w8=,tag:VRRGzW6v1/QLPLZ1rvy9jA==,type:str]
storage_encryption_key: ENC[AES256_GCM,data:TIV+VeH91Ss6fqFk5Ss8WdagK+ngd1nlsB2lq1CKMFMadv8nvWnmtitL8jW5E7fO+P2gsXPjVSybAlHwjD7BbA==,iv:maajcnHwFQGPY87fDlF5c6TyHy786oaeNJWs2+DLG3E=,tag:AjzCf8/J1OgEV3CLBoi/2A==,type:str]
users:
    - username: ENC[AES256_GCM,data:5MLar84=,iv:Mgy9+2quUfVdiwVlK6FEEY/5e+lRqkl7J34j1/CKR9I=,tag:K5IizXH3nz8wt3rRnWMOiQ==,type:str]
      display_name: ENC[AES256_GCM,data:IrdzpKM=,iv:B+rEavNHhXqg1jwKaYTzDDZNJgF7gtGjJaJEypSslSU=,tag:bLJ4yPt9COeoUpFi3m+B3A==,type:str]
      password: ENC[AES256_GCM,data:A3ThLAFkXVY1juga9ywq634W9+RT9icQo1dF9iaZvi4z0AtIFGbHDNGCtiGd7qndv/aCV6bHOSuRH3YcYMhG7v83VvsZXjzPMb3NtyIFeUPkCN/TlGhrqGTnzE/YJhKjfA==,iv:jLNfqyaBwhF1mw367c7N+64XGQE6FMne9AgKOomzHHw=,tag:t1a07XFV9lZtwVcJ9KBW/Q==,type:str]
      email: ENC[AES256_GCM,data:LH5dgP0RT8ECsqn4SRMsdaXFDnfF,iv:KqOuuZxjMUDl7dH6pkUI3ZUYJZYtWeMn47h1h4Dlamk=,tag:na/vjA2OR31wle5+1VOY9A==,type:str]
      groups:
        - ENC[AES256_GCM,data:CnynPKW9,iv:iIKS+CxGkRucYNTltpw4HfOeQJik1esuJJOdlrWM0gA=,tag:98UE84LGUbeu487pGW9xCg==,type:str]
        - ENC[AES256_GCM,data:8wScT8E=,iv:WsLOgkzuaeJqSyl8YDiTfC9HD1X2GGBObuFSfok1KPs=,tag:PRL8EpgK7rz2jm/eIbVyjg==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTStFWHpBUHdMQzFQdGtG
            WXZSKzBucjhxRlEvZ0JEa2x1UjcvNEI5MEZvCnczamR4bUU0clVWbjRZNXpOZTFx
            dVVwQ2xlaWd5T1N6aG8raUFDTmhhUnMKLS0tIFhRRWtlWVlxQkJzR2J4R3dTbk1U
            N2pXTzJLakhJMTg3Sm82R3BCRUFPd0kKCiSVRcpDTUDlrqGqsuFFy+Byj1CQ+kr5
            LV/cesE7Ao1Wyh34kX9Y7dSPZBaB4oaXi7vk76d/agbnm+pQ610sLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T14:43:13Z"
    mac: ENC[AES256_GCM,data:WjppAqFhcjVR29fVsAqfySjJ/wHD5wHD/Hu8iOp4vxROYZsPJVfLgGQYML7fYrSBoYBRXCghNnENqVHdZGWgn2SAL/wmmLIcBo+IpVm+IumHKPvnYeCPI/1CUQNQfNryu10y2/lsZK8w9RL6wOkIDMgjV16Um536pIaW91Oiy80=,iv:ZM5+GlyATny3XgB1zUlcmz8Qum7IB2DSCFupQyLkgBA=,tag:+tiVtNn5qkECh4b6QCb3EQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
