truenas_host: ENC[AES256_GCM,data:INEXEbdX5c22IQ==,iv:nVwBmCv8GFW8YGFzRNzl3hetesfNRSAoYIkN0+JweD8=,tag:hx4V6tcUS0gZXhUtu6bFPw==,type:str]
truenas_api_key: ENC[AES256_GCM,data:2gEfqLjbhgXbXUOREdwGO2OYSehHVmVbEX7mfY3vVjUE6wRSOCzNM+WQfgEHrynTo/CSH4zge8wj5nVEqhxC1WQW,iv:aI11Pfkn0bYHbNxMkb/n6djZdzlBCScI1cB/HebsnGg=,tag:wYrkv47AvTwkKXTj7Xx97A==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOHpyMkZYellsZFp1UHBq
            T29ENUQxZDY5UjFGNGxrUkFsdmNXakpINmxZClJkTlU0KzlQenkvNXpFdGRqYlpu
            M0ZiV0l6RHUwaWFES05iOExXKzB1SXMKLS0tIGZHUUdxZTlma2RHYUIzS25TVkJN
            dWRBZXhhMTBsUTNUVnVORFcrZ0YzTEEKd9dNnstzanDagxKYgwh6Romb7AJ2NV/k
            dzr4DN7QMV4uzTZoQiJzqTTi9dBBwjJdtr60L7LkA0Q7yjJ7ayF8UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T07:09:55Z"
    mac: ENC[AES256_GCM,data:GAPDEB62IxMPTSow1ftGoUNdA0ALQ7X2pYX8L5tLeJkZs9R4Z42WQiimaw9GXPtMMSEIztGTzDk+tVvVht6o8TNXL5h7FIkSSEK9HepU0KQ3tI23r0r6cp/pq2tnG9niyPMkuYOW18XT34nkN4MGhtWgv8tOnMzxY8T6H/HYRRA=,iv:SY14lRyHLSKF+DQbJ91zs7kay3xROd8jxwqdddyXlHc=,tag:SdeozKRekqWZC+gY0njWpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
