aws_access_key_id: ENC[AES256_GCM,data:fY2D4YDDGUG3Z+5SOzEQ/EkoTmIXCViG8A==,iv:4qPqRweQ6z3n1Z9BeQhd6yKbnovNs4EViV/x7TaeM/s=,tag:lTXRUVdvoQ/R7Q+sgWmIwA==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:NQ0gse3SZ3rywwK9flyQDVGn8T2OCFHfHLdGq5CMLw==,iv:uW1z0YbsC0vIKmpupsYH6g9LqHgMQUMy6iR5ftnOlNA=,tag:8MehPay8tgv7AMPen++fcw==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOFNIMitid0dwQjJaa05m
            TmlaZDRoMjl0U0MyQjhMWmtBOUhBV1k1c0NrCkxhTmlEV1hUVHZWVnVlYitZOXpV
            WCtaN3FKcjZYVXJWQnp0bk1vMnVrQlEKLS0tIFlTbVY4Rm9tL0dvMG5RT0FhZTZY
            VTZ2UmNxNlljSmxFYlBwbmpDSklVRDQKhcA4e3qiDadnGmGI0xWiX1DqMLZtlh+4
            aKqSnlb9Z73ZI8iBCDETdWpqQHk3U8pHnTd9NvwdYNV33+D/FjJTBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T10:15:12Z"
    mac: ENC[AES256_GCM,data:0FP/AoyhJflMfNzDJiGmJcJJVbPxmGVuUzlf/LO4hD1/Jy/ew9dL5a3RRZH98IjTaIVqVr2kwQ1wcA8VIpbWebiohGK0JbOzqXzxUhef2P2qdqIdfR8RW5EyXOCnDXfdqHjAvnbP6i0zHAcdN0h3XgF4d6dPl6apKc3t6Ueo9Zc=,iv:BLzAobO6ih9SUikEPJLFoVWBzIfOrVN0YF5hxBuJN/0=,tag:WRjWagy4pMKea+SAxTGO/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
