creation_rules:
  - path_regex: 'authelia_vars\.yaml$'
    age: 'age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz'
  - path_regex: '.*\.env(\.sops)?$'
    encrypted_regex: '(?i)(PASSWORD|PASS|TOKEN)'
    age: 'age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz'
    file_format: dotenv
