ldap_base_dn: ENC[AES256_GCM,data:DpgatX2WqaygHtDUU2roITo=,iv:bX5fgGEsyvMorHEmuQ8HxsgRKj8IofxPRCIuj4O2dfU=,tag:4f4Dj29yJqM8U3L8XuncCg==,type:str]
jwt_secret: ENC[AES256_GCM,data:43NeIJz9JFUSmLzQV0QZ1mbQQJXwgcuWYwRp55ldi2k3yFHQIeEBWo75XXme0bnYVR0zLAweY8VoXXEwf/YIHw==,iv:kPBEO/RQiDdlV2EZiDwlt8Ilc3MbYcP43CKWVLwMN0U=,tag:buC+2Af9Ul3bDqpo3mou8w==,type:str]
key_seed: ENC[AES256_GCM,data:wGMaGuAcBIeXEHsUbcj7xN9r85PyzfzI7/VQ58r/PqKRxTGH2au1yeDz1Ku7bMlBwTolzmmYFtYMzsRaLPSCng==,iv:/LJHeTWwvTGAXqa6VSpCBh2Eu9Mv0P7uY0HRFzRvH5s=,tag:cZ7J0qo0RIWWyZTbcmlzNw==,type:str]
admin_password: ENC[AES256_GCM,data:PRxun8J0qxZsNVK91NJEeOYVXU7c0vDhn16JSbqOozr2GhBEkkdmELLD0svNFJlSrqcn2fbkfwNGFClT1r2nPg==,iv:EbfS9pUZwvs0WoSxExXndjrMywqjvFAExQEL2Lrnss8=,tag:aotRtKeby1kw2DCQSnJ5gg==,type:str]
users:
    - username: ENC[AES256_GCM,data:Fp+ILyIXS/g=,iv:ffDph+95o8bgO1kIJA9BEoGC57fAVeuKXH8UjtPDujk=,tag:28GTvfRdGNu4S5xW6sr2cw==,type:str]
      email: ENC[AES256_GCM,data:guIcvpORIG7bMBXNKjwvIICD+5xiQ1x5IcAtAUUL,iv:l2u+o9OuUByGdRTWFyuaZD5AHLggOa7ePlc9/MxJL+A=,tag:apKrlK1oX+A+QZy1dITjuQ==,type:str]
      password: ENC[AES256_GCM,data:yVHhcPGxuijcSQvjCkbVPQrBBtuqI8qB2MLWFNSb+PmmHr84uwMVEXK94HrzTl4c2/f9RurTVxNhikr5y5pD+g==,iv:+EANSHZReI1E8AlapT9D/LKzyso6mGfF1tTHerYkfW4=,tag:fzGuCW1is7Z70hjp2O8gAg==,type:str]
      groups: []
    - username: ENC[AES256_GCM,data:GTDjW9M1tyA=,iv:Aw36PKWL7MF/xLVUsvBWEDOK1/gNWj1TS8so0JOAt5E=,tag:fYPu9TYfEsCxg6YATGKVvQ==,type:str]
      email: ENC[AES256_GCM,data:VwAeeh0SZkCTjgpcYeHeaojI7XXt2esfsdZ/Smii,iv:ugHhTl8xdXKjnkT9EZfsvrwWmnVaUrNvdLQHRZV76JE=,tag:G0IZ1dn55KvdsNsO+CmCJA==,type:str]
      password: ENC[AES256_GCM,data:uxaig9P3kF3zDTgyAjShBUfh6w5I8sYEJq0bIsjbBDmeAdkldswdWJoIQMTK/sJDj6GLOu/lRvST8dYwVi8rfQ==,iv:ZBzGe2TJw9E1h7KQQysSHY2n38laHdSeWLJS481KP4w=,tag:tUgEBWuQ5YHlS2aogAB5uA==,type:str]
      groups:
        - ENC[AES256_GCM,data:59M07hqLZAIoPVHj1RCYQEiC9lEfYg==,iv:cLMQ0wK7sG4L/HfcIzAzxC6U/RAFstBUF7kUo4+yxKc=,tag:UeciVkkyokPqrLRhQtnjCw==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT2w4N0lwMUlYUzJvODZV
            dTNhSUV2elY4T2V6aXo1RjA1aTZOa2cxVEdRCm9UaVQrMmVHS1UrenRHb1hkSnhn
            R1VNa0RzKyswZlFKK3EwckxFRndua2cKLS0tIDJnY2hWdnF2RWZEK243Rk8vb3hZ
            cjRORUFwdkZ5WWF5RkJWWGViR0kwdTgKkDt8hgrIjoEhlfnS7VM+DY/BkjREbNg7
            Vw6hz6nM0JV884dXewIkJGDR9qVD+2KZJg0gKC36XwhgMl455ZVqGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T01:19:10Z"
    mac: ENC[AES256_GCM,data:pXam+jnqRv7JaRqNEVTOT5kR4meNBoKTPtauA0chHouB7omfi/Fho/YfwmJydoNICezP0Av77CMZRXvgkDeTwzvX12vX2aZRwVfFiumUkrW6cKKOmecmR2B4Onclww0gcgmqxZrfE1ZLuYNCNWfCXvDkg6MSGVIYWGv0tTOpAN4=,iv:IDrunSr5W3JcTW34JOOyvsfXBqycg0DJKYFB2R9LJ7s=,tag:jGFT4IIrg2bC2l2GDasF/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
