domain: ENC[AES256_GCM,data:jjwGmu0oj2Erw9c=,iv:H2ROHLMLSpe9Y+nixMsHwLTksGNkDDdeDsH0KaYlbC8=,tag:R38b5A8sInEcRgyYFrj7Sg==,type:str]
authelia_url: ENC[AES256_GCM,data:U1LM9oeWwCfQOHlifRqqj//MlmYMlqeN,iv:DJhfZHf/VLfwAf4ZOKdGIQoTA0gPA9kp5VZMfKNtCe8=,tag:UYk9YMq69HQRCOntbnAE3A==,type:str]
storage_encryption_key: ENC[AES256_GCM,data:Dozz4Lzsg627eP55ifoHdf43uKZIPus82QaUYHEGs+OGTv0FmJQfoV1aYdlhs679obsYPR+vc1BEBXplLdZVog==,iv:gf7yIXiQiR2PIBGDo94kzHXeBg3pCXOH+kp6FuqeRRM=,tag:FTg7H6Q50/XinkwcO58nsg==,type:str]
postgres_password: ENC[AES256_GCM,data:JMaU6Zhx7kaEl+aL9r5tRaEkOHWw5/Q0+nrOGnnH9NjiZHPY8X4Hz0boXtBrHoqf8/OVOcmqt1xzRxqBfLdG6Q==,iv:xYU2mIfmVFlJSkpZWvV4V9UvJpGj5CzIpLbgwHb+GF4=,tag:07dk+EuvsAjV7BDJbXXDvw==,type:str]
jwt_secret: ENC[AES256_GCM,data:x8uGI8mjoUA2tecRlldAZo7Gw/AF2TMeZsmqv4l+U21Q2XiG4+C6Bjub/hrEluWYkw55XeE/NO9AWw3rmyj4l4ZglBmJh415Rb/3uSGbA9vHO/iQx9PnGOOCxNc+8XBwgC1iNduApkrYPTSE7vDpy+A14ipVtGfbNjAr7VDtyRk=,iv:uY5WjDRN9KqpiMGyNs+5vJuqtvSE+Wt8B0UjF6PwUfw=,tag:VceIjaEYmEDAU0B4nncyXg==,type:str]
smtp_password: ENC[AES256_GCM,data:qoVn9nMChf7luXnGhobKlQ==,iv:xzDSUG36tS8A3W6ZvmZA9cL/7mIerLv3MA6XBpqixIU=,tag:tb7hq93fM5fy+Z+jHSb+lw==,type:str]
users:
    - username: ENC[AES256_GCM,data:sR3em8v3H2jYmb0e,iv:vTCQWy6WiVw22ZWFN8eZHO/LkqeWlfM6yuE34dUcADY=,tag:VeKXPyK61l3H9M4xeYGCrw==,type:str]
      display_name: ENC[AES256_GCM,data:/FDUO+f8xP8pXi/t,iv:8t/IiIwy2tRLU5R9MzpA8/KgYByzp0IEcrYmTcxSXt4=,tag:sG9IqAThEn1j5vtRwn+Vtw==,type:str]
      password: ENC[AES256_GCM,data:5mFWq03W7tiRlNU6+f0p9nLgHjIXMtMn6w3fziXKXQMzFKYW22mkZ5rfMCmElrCWXCdBcFYwyG2DwAkWDhwcLAej6E80q6HSMSt8v4XLlhsrZhub6zBOoTOOgIJUxJwr/A==,iv:VDrjtlh3V7lO2wQ0cTYPTkO0VBggozZRZPxDk/qhUMk=,tag:LL2i7adjjfXR69W5bQMNSg==,type:str]
      email: ENC[AES256_GCM,data:nJGLo6ByUXBpo1VE4ZcLVR5ueW9Y,iv:4y3G1z0DpvHe2ZLvqG2UZsoaAU9ZHCm0HBzE6s8bp1w=,tag:aWiQxOLUbpeoJMb+2BGSUg==,type:str]
      groups:
        - ENC[AES256_GCM,data:g54LMsM=,iv:+LdGpjeifVjmVpU+O0xuALyqoZMve6NBPdguBdKTvMI=,tag:vRI7+fBvFUXRBzmnyfPEOw==,type:str]
lldap_base_dn: ENC[AES256_GCM,data:gzj3NHIO5F06mbUMvs3qgbo=,iv:ysU0KD6XVi5UynyY2DjjRxItbi+Jl4YnyW2fWHTFwRY=,tag:kS+ZnQauz3Xlb7vBIUdRsg==,type:str]
lldap_user: ENC[AES256_GCM,data:RSZg0yv2XqlwaO9jbEtLuBkQYEVzSRSc6ZKY2iqjox7k6yb9y6q8Rw==,iv:2WIxDS0Xzx2/ZzHLlyhnugaX7SJGlhMeysnsNZlCJFM=,tag:TLVVBg9xji3+JzqGyX7CVQ==,type:str]
lldap_password: ENC[AES256_GCM,data:h9CIUd6qM8v+Rh2sp1rdtbqxhnXHEEN+7dU1hIGr7zeInxEmDP1aYaFF4fbKdSbjTFIA1exJ0dL8cbrq/Iyqhg==,iv:6Y4M1uzzZJ3xCoRhBXexmVJdWtTIyO6WPYcMUmZiUvk=,tag:Eh6+3/+MOnEXxm/5wGStCA==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNXZOayswQjd2bG8vRnFr
            UXcxREZpZUJUVEFxVmgyYzNkYWQrSWZlRGxFCmFMeFlxV0FTYTloVGQ5UmJYOHJD
            bFNwS3lRY2V1TmIrSGZEQmVlZEJ1OGMKLS0tIHhaQ3p6YmFpdmlYSWFmL1ZUblV1
            SWFpNU56cjZxSkh2YlNoMXRWNzNDcEkKLAFy11LNkhsCsaAsXRNTEID4U3RwdopP
            2EUxXTzrHl6k+MJtZPUAe0yBkorHPd0uL+ybkJbjoY5HA8P9SQXUGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T02:16:41Z"
    mac: ENC[AES256_GCM,data:Go1pLI7+1NXRkvFo8xDqSbvT2YPZudnIM2crHabuQGYEtK6URnEkC23ReBtTvrmcvB/7t6X1F7Ziktfv2WCyey7ghT81ZsxZquVL1JuBQKLxsY5iz3NZYf5yKdoBOWGA8ZUpBPVHK8kBJg29h2pkZMcBpGvyQZp3FS9nsa0zyKI=,iv:EWE06+f+enWNGgTG2jwNZwSCggtHHY90ymmHHqJ8hao=,tag:O7wBGHDXhktI0Bm/qDQ76g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
