domain: ENC[AES256_GCM,data:H66cYMIbttL5JvQ=,iv:0YlCWf1PYg8Kt/yodVbtsJWAMYsKUK2DE2EDPH3MJhc=,tag:gotXKhKrSsm2q5EruvEMPg==,type:str]
authelia_url: ENC[AES256_GCM,data:J8cii4WSw2v0U2IcGzCH8eiUQp6gTGit,iv:2I/5YeRXak+zCbBLBr5ccXkaXhbK7pldG/6VKaSBX2Y=,tag:12wx8UcsbTxAemIOAbATcQ==,type:str]
storage_encryption_key: ENC[AES256_GCM,data:kDF0XnsTklmdUlKz9Eubv3MNFlmtAffPxZcaJ8NtANiz6ZqvrHIFiJKyXbGrWlF71uYHRcjgQZiOS6CCPrd5vQ==,iv:OM8eCYOpbOue2YnVBoh3G4UV1gcGl6rib7iJuTium58=,tag:mYvTTjH97pisxNytEqW08w==,type:str]
postgres_password: ENC[AES256_GCM,data:hHAxZvYbbMKg7qi7F/9Wq+4XI1XisgkuTzVtd7VgFrLva6o50VD2pu5PmekiKgNeESKpmsKJIn4G8UhrVhYM0A==,iv:X1haevtMlJdmMA5B5dJXNf7Kt25OEriBzBE04jJELio=,tag:Fea1tReu4WFak7rhzMJDQA==,type:str]
jwt_secret: ENC[AES256_GCM,data:cWSgL2BJSdZTEfS3U/YkubYIWroCgWXisspJC1VwZ4+AImuO6puUZAacac3VGd8uW9RImK6IQdK/nP2lbPuMI0QnZkMwW7WVLTAmNRgVyU4DsAJSe8UN1Ayzq/Tt+Qvi55CLTEmK1qTycnuMbQxZ2LOqS+lepD2MLe56EKQF3uE=,iv:CvSJZwr5PVjRIFiTQg0EORaL89Czr7wpitq3w9Pwu3w=,tag:YBc2YYXAQX4ziw6OI3QizQ==,type:str]
smtp_password: ENC[AES256_GCM,data:C3VrHQRaHisSCN2YM+NZSw==,iv:NYBZW4hF6zIhL67LsbNJFe3G5hcbF1Z2U8Xx5hlVrwQ=,tag:6aKtWkfGhD07vHDwH/lUwQ==,type:str]
users:
    - username: ENC[AES256_GCM,data:021ZElE=,iv:NteFMZtuCeiDDEdenxvIsdCnZBAB2kGPmnrz78+s6i8=,tag:p3jpR70HBlT4fv5bYjzT0A==,type:str]
      display_name: ENC[AES256_GCM,data:mH8w210=,iv:pgAlsFD/V/JKSK3SrWn7ta5Ab4oTyebrpAgMlSEfCLI=,tag:Bdtd3lw9G1I2khJRlIDHcg==,type:str]
      password: ENC[AES256_GCM,data:oR7xfgqlUES8yXdPHjlarqo8lNL4YG/Do4ozP/f7vVUrgTniwI9++L0DxKxj8ae0/C5KM9VnB46ydN0NDEirxprmWDHz4g75OvK+M/SCM4EU8VJnyfow37LaVYxYGG9aAg==,iv:5shj67bIhgdDO1ptdywdzx46kzfx8x1/eVn1WA3KXGY=,tag:hKFuJkCQhS9yjpGhKyZEUQ==,type:str]
      email: ENC[AES256_GCM,data:Z0nf987XTjfzmfQyWqhDPNwiKau9,iv:eHXnVzMY06uOcVunWYKt/AYO12z9xwfNlQdneI8UWSo=,tag:41q875s906MnGKoQhFSLlA==,type:str]
      groups:
        - ENC[AES256_GCM,data:cRmWtiVw,iv:DsSk2768UMAPdpDj0p/Hox9yYWdqPr8rnURSt/HbHHA=,tag:Qmr8UKDp96FQnle5Lh8sfA==,type:str]
        - ENC[AES256_GCM,data:iJGLH6o=,iv:dI6dRZuY3p1NPvyrHAXuIhD+Harbrv3w5U8OxbDciME=,tag:zEahc3lKlcAIlhveoI2DDw==,type:str]
lldap_base_dn: ENC[AES256_GCM,data:bjltwrTiM/5/fQ/ZM4doNQQ=,iv:bKTffMg+v82JrzSiW7lb7yI3TJY13aeJ7uU6A7MKGVg=,tag:MXiSncbYXFtdv5hrbOTXAA==,type:str]
lldap_user: ENC[AES256_GCM,data:ryVh8iWveROLjhJVp5soH8CXwjFAFnMQ86X/7QK2Ewfusn1WVWFOJA==,iv:HC4LeLuCBvPFS3zeT4h5eYxnsWRPxqcFh+va1lY1k9s=,tag:v8rhplgkEVeKHPXlv9iqNw==,type:str]
lldap_password: ENC[AES256_GCM,data:ErmZwa9DLoKM1qtXSgcf7Edrm1vSTIJlJgdY25MVY8God2QVjB4IXWxEOmvYzZ5EKdkKPB5RHx+km8s/VFXsOw==,iv:1mRGAI6gD8eFrj6GcuSE1czNIzZhJZMoq24kOPqbNtM=,tag:yBT293mGawEN5r/BCraL8g==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbGhnL2RZeGszS1Iwcm0x
            Nld2RXdRQThEME9OVFg0ZmJYOWtWNFQ2RW5BCmw4Q3E2dk1aQ1RDS3NnTXdxZjVD
            dlkxcnNYdlQ0MWVvdFliYndvMWxsZjgKLS0tIC9KK3Fhek1TTXQ3VzZ5R21FNkYx
            cUo3OXBOZXBHQlNQUlhEVmh4ZUlrVlEKOV7GsAKmXyEnGRkIVrJZbmHIem0j+2oF
            Oucl+Ezl1RpQRdF6V6BYpn5pUSM9j7m+xvznz4Pl1thrxiq3zcdoNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T15:07:15Z"
    mac: ENC[AES256_GCM,data:i129M8gz4iMbwWET167OZrhlTZ9gMyr3KGD9evVPT1yh04S1l0oIVyKNDCddPs427EwBThhviEhNfDrPZVvG2BxGzhl2LNHRdG+anER7M7kH/zK0ljx8VM4oEAg0HAsNoqLF+zVd1sA33QywVUHRuoHONf7IexP3e8Hi8IJOATQ=,iv:fhUV866o6couqjKedrt/tu/nBCSy/liU0Ow0KUNSics=,tag:A41KfT7WG5K0DCNKMGG5sA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
